alias: hass2hass - switch - command
description: ""
trigger:
  - platform: mqtt
    topic: hass2hasscommand/switch/+/set
condition: []
action:
  - service: |
      {% if trigger.payload == 'on' %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
    data:
      entity_id: switch.{{ trigger.topic.split('/')[2] }}
mode: single
